name: product_prices
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  logging: ^1.2.0
  provider: ^6.1.2
  go_router: ^14.3.0
  intl: ^0.19.0
  lottie: ^3.1.3
  shimmer: ^2.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/add_to_cart_animation.json
    - assets/lottie/empty_cart.json

flutter_intl:
  enabled: true
  arb_dir: lib/src/l10n
